schema_version: 1

context:
  name: ldas-tools-utilities
  version: "2.7.4"
  ldas_tools_cmake_version: 1.4.1
  ldas_tools_al_version: 2.8.0
  ldas_tools_diskcacheapi_version: 2.7.9
  ldas_tools_frameapi_version: 3.0.7
  ldas_tools_framecpp_version: 4.0.1
  ldas_tools_ldasgen_version: 2.7.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://software.igwn.org/sources/source/${{ name }}-${{ version }}.tar.gz
  sha256: e06fd42ff7e9a99478db73e5b715e08d475369b91b23748d4234afb576077f97

build:
  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then: /usr/lib/libSystem.B.dylib
    overdepending_behavior: error
    overlinking_behavior: error
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake >=3.6
    - if: unix
      then:
        - make
        - pkg-config
  host:
    - ldas-tools-al >=${{ ldas_tools_al_version }}
    - ldas-tools-cmake >=${{ ldas_tools_cmake_version }}
    - ldas-tools-diskcacheapi >=${{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi >=${{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp >=${{ ldas_tools_framecpp_version }}
    - ldas-tools-ldasgen >=${{ ldas_tools_ldasgen_version }}
    - libboost-devel

tests:
  - script:
      - ldas_create_rds --help

about:
  summary: LDAS tools utility programs
  homepage: https://wiki.ligo.org/Computing/LDASTools
  repository: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
