schema_version: 1

context:
  name: ldas-tools-utilities
  version: "2.7.5"
  ldas_tools_cmake_version: 1.5.0
  ldas_tools_al_version: 2.10.0
  ldas_tools_diskcacheapi_version: 2.7.11
  ldas_tools_frameapi_version: 3.0.8
  ldas_tools_framecpp_version: 4.1.0
  ldas_tools_ldasgen_version: 2.7.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://software.igwn.org/sources/source/${{ name }}-${{ version }}.tar.gz
  sha256: c000cfdfc20e7a845b07cf7e97c4c302797782f027a973b64436fd539974cba5

build:
  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then: /usr/lib/libSystem.B.dylib
    overdepending_behavior: error
    overlinking_behavior: error
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake >=3.12,<4.0.0a0
    - if: unix
      then:
        - make
        - pkg-config
  host:
    - ldas-tools-al >=${{ ldas_tools_al_version }}
    - ldas-tools-cmake >=${{ ldas_tools_cmake_version }}
    - ldas-tools-diskcacheapi >=${{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi >=${{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp >=${{ ldas_tools_framecpp_version }}
    - ldas-tools-ldasgen >=${{ ldas_tools_ldasgen_version }}
    - libboost-devel

tests:
  - script:
      - ldas_create_rds --help

about:
  summary: LDAS tools utility programs
  homepage: https://wiki.ligo.org/Computing/LDASTools
  repository: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
